import { useState, useEffect } from 'react'
import Head from 'next/head'
import HeaderNav from './HeaderNav'
import FooterNav from './FooterNav'

const Layout = ({ children }) => {
  const [mounted, setMounted] = useState(false)

  // 👇 min size @ 1024px
  const navGlobeSize = '88px' // 88px

  useEffect(() => {
    setMounted(true)
  }, [])

  if (!mounted) {
    return null
  }

  return (
    mounted && (
      <div
        style={{
          display: 'flex',
          flexDirection: 'column',
          minHeight: '100vh',
          backgroundColor: 'black',
          padding: '15px',
        }}
      >
        <Head>
          <title>Create Next App</title>
          <meta name='description' content='Generated by create next app' />
          <link rel='icon' href='/favicon.ico' />
        </Head>
        <HeaderNav globeSize={navGlobeSize} />
        <main
          style={{
            background: 'inherit',
            flex: '1',
            display: 'flex',
            flexDirection: 'column',
            justifyContent: 'center',
            alignItems: 'center',
          }}
        >
          {children}
        </main>
        <FooterNav globeSize={navGlobeSize} />
      </div>
    )
  )
}

export default Layout
