import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <main>
        <h1 style={{ color: '#ffffff' }}>Welcome!</h1>

        <ul>
          <li style={{ color: '#ffffff' }}>
            <Link href='/audio-globe-grey'>
              <a>Audio Globe Grey</a>
            </Link>
          </li>
          <li style={{ color: '#ffffff' }}>
            <Link href='/audio-globe-black'>
              <a>Audio Globe Black</a>
            </Link>
          </li>
          <li style={{ color: '#ffffff' }}>
            <Link href='/colour-globe'>
              <a>Colour Globe</a>
            </Link>
          </li>
          <li style={{ color: '#ffffff' }}>
            <Link href='/rocket'>
              <a>Rocket</a>
            </Link>
          </li>
          <li style={{ color: '#ffffff' }}>
            <Link href='/combined'>
              <a>Combined</a>
            </Link>
          </li>
        </ul>
      </main>
    </div>
  )
}
